### ISSUE TITLE
Charge % calculation

### ISSUE THREAD

**Issue by pastukhov** [wellenvogel/usvwatcher#1]
Hello!
I made a Prometheus exporter inspired by this project. You can look here https://github.com/pastukhov/ws-ups-exporter
Can you please tell me how you calculate the charge %?
I found `p = (rt.loadVoltage - 6)/2.4*100` what do these constants mean?

**Comment by wellenvogel** [comment]
I guess this is just from the waveshare example code. Did not change this - and seems to be correct.

**Comment by pastukhov** [comment]
I asked waveshare and here is their answer:

This formula is used to convert DC bus voltage to percent of battery charge (SOC). The constants 6 and 2.4 represent the battery's minimum operating voltage and the nominal voltage difference, respectively, so the numerator part "bus_voltage - 6" represents the voltage range in which the battery is not fully drained.
 
The denominator part "2.4" indicates the range from the lowest voltage to the nominal voltage of the battery (18650 full charge is 4.2V and low charge is about 3.6V),
 
The overall expression therefore calculates the battery voltage range as a percentage of the entire voltage range. Multiplying by 100 converts the result to a percentage.

**Comment by wellenvogel** [comment]
Cool, many thanks for sharing this info.
